<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_36.00000</name>
   <tag></tag>
   <elementGuidId>a217adb8-bfce-4498-9bd0-95db7eaec8a6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>dynamicField.getIsReadOnlyPlainText() &amp;&amp; !dynamicField.isFieldTypeText()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aptQuantity read-only-plain-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>dynamicField.getStyleObject(dynamicField.properties.Style)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Apttus_Config2__SellingTerm__c</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	36.00000
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[@class=&quot;content-container&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;layout-single-col ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;main-cart-wrapper main-cart-wrapper--overflow ng-scope&quot;]/div[@class=&quot;main-cart-container--positioning&quot;]/div[@class=&quot;main-cart-container&quot;]/table[1]/tbody[1]/tr[@class=&quot;row line-item-row is--open prim-attr-row ng-scope&quot;]/td[@class=&quot;cell main-cart-col DOUBLE main-cart-col--double&quot;]/ul[@class=&quot;submenu submenu--chargelines chargelines ng-scope&quot;]/li[@class=&quot;charge-line-col charge-line-first&quot;]/div[@class=&quot;fieldtype-wrapper fieldtype-wrapper--DOUBLE&quot;]/div[@class=&quot;full-width ng-scope&quot;]/div[1]/div[@class=&quot;ng-scope&quot;]/dynamic-field[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@id=&quot;Apttus_Config2__SellingTerm__c&quot;]</value>
   </webElementProperties>
</WebElementEntity>
