<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_select2-choices</name>
   <tag></tag>
   <elementGuidId>83d76bc6-6840-442f-aa41-6506343407a8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-choices</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[@class=&quot;content-container&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;layout-single-col ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;main-cart-wrapper main-cart-wrapper--overflow ng-scope&quot;]/div[@class=&quot;main-cart-container--positioning&quot;]/div[@class=&quot;main-cart-container&quot;]/table[1]/tbody[1]/tr[@class=&quot;row line-item-row is--open prim-attr-row ng-scope&quot;]/td[@class=&quot;cell main-cart-col MULTIPICKLIST main-cart-col--multipicklist&quot;]/ul[@class=&quot;submenu submenu--chargelines chargelines ng-scope&quot;]/li[@class=&quot;charge-line-col charge-line-first&quot;]/div[@class=&quot;fieldtype-wrapper fieldtype-wrapper--MULTIPICKLIST&quot;]/div[@class=&quot;full-width ng-scope multiPickList&quot;]/div[1]/div[@class=&quot;ng-scope&quot;]/dynamic-field[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@id=&quot;ext_FlaggedAs1&quot;]/ul[@class=&quot;select2-choices&quot;]</value>
   </webElementProperties>
</WebElementEntity>
