<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reprice</name>
   <tag></tag>
   <elementGuidId>3cfb91b3-18fd-4519-9c26-8514c8433f92</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>(action.ActionName != displayAction.labels.displayActions.ACTION_MORE) 
							&amp;&amp; !((action.ActionName == displayAction.labels.displayActions.ACTION_REVALIDATE) &amp;&amp; !displayAction.showRevalidateButton())</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>displayAction.doAction(action)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>displayAction.isActionDisabled(action)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button Reprice active-true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Reprice
			</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[@class=&quot;display-actions&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;display-actions ng-scope&quot;]/div[1]/display-actions[@class=&quot;center ng-isolate-scope&quot;]/div[@class=&quot;display-actions-block-bottom center&quot;]/span[@class=&quot;ng-scope&quot;]/button[@class=&quot;button Reprice active-true&quot;]</value>
   </webElementProperties>
</WebElementEntity>
