<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Product</name>
   <tag></tag>
   <elementGuidId>8996b72b-147f-40dc-b358-27e44274cb9e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-cart-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            
            
            
                
                
                    
                        
                            
                                Product
                                
                            
                            
                        
                            
                            
                                List Price
                            
                        
                            
                            
                                Base Price
                            
                        
                            
                            
                                Quantity
                            
                        
                            
                            
                                Selling Term
                            
                        
                            
                            
                                Delta-Quantity
                            
                        
                            
                            
                                Start Date
                            
                        
                            
                            
                                End Date
                            
                        
                            
                            
                                Adjustment Type
                            
                        
                            
                            
                                Adjustment Amount
                            
                        
                            
                            
                                Net Unit Price
                            
                        
                            
                            
                                Allocation Percent
                            
                        
                            
                            
                                NNACV
                            
                        
                            
                            
                                RenewalACV
                            
                        
                            
                            
                                TCV
                            
                        
                            
                            
                                Flagged As MultiSelect
                            
                        
                    
                
                
                    
                        
                            
                            
                                
                                
                                    
                                        
                                        
                                            1
                                        
                                        
                                        
                                            
                                            
                                        
                                        
											
												Additional Non-Production Instance - Asia Data Center
											
								
												build
												
											
							
                                    
                                    
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
														

	Subscription Fee



      												
                                                    
											
										
                                                    
                                                    
                                                    
                                        
                                                
                                            
                                        
                                        
                                    
                                    
                                    
                                
                                
                            
                            
                            
                            
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	USD 1,250.00



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	USD 1,250.00



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

    

    






                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	36.00000



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	5



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    


    






                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    


    






                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    
--None-- 
			% Discount
		  



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

    

    






                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	USD 1,125.00



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	0.00



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	USD 243,000.00



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    




                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                    
                        
                            
                            
                                
                                
                                    
                                        
                                        
                                            2
                                        
                                        
                                        
                                            
                                            
                                        
                                        
											
												Additional Non-Production Instance - AU Data Center
											
								
												build
												
											
							
                                    
                                    
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
														

	Subscription Fee



      												
                                                    
											
										
                                                    
                                                    
                                                    
                                        
                                                
                                            
                                        
                                        
                                    
                                    
                                    
                                
                                
                            
                            
                            
                            
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	USD 1,791.67



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	USD 1,791.67



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

    

    






                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	36.00000



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	0



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    


    






                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    


    






                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    
--None-- 
			% Discount
		  



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

    

    






                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	USD 1,791.67



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	0.00



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	USD 64,500.12



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    




                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                        
                    
                
            
        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[@class=&quot;content-container&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;layout-single-col ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;main-cart-wrapper main-cart-wrapper--overflow ng-scope&quot;]/div[@class=&quot;main-cart-container--positioning&quot;]/div[@class=&quot;main-cart-container&quot;]</value>
   </webElementProperties>
</WebElementEntity>
