<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ACCT0000055</name>
   <tag></tag>
   <elementGuidId>7cc3afc1-fed8-48bf-bfa1-c2c6504e20fb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glide_ref_item_link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sys_id</name>
      <type>Main</type>
      <value>8fc3f7ae0a0a3cba019da3d205ede759</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>top.window.opener.reflistPick('sales_opportunity.account','8fc3f7ae0a0a3cba019da3d205ede759','Johnson &amp; Johnson'); return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCT0000055</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_sales_account_8fc3f7ae0a0a3cba019da3d205ede759&quot;)/td[3]/a[@class=&quot;glide_ref_item_link&quot;]</value>
   </webElementProperties>
</WebElementEntity>
