<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_id(new)divclasslookupdivcl</name>
   <tag></tag>
   <elementGuidId>ca67083d-20c7-4020-a69b-2102b5739b2d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>katalon-elementInfoDiv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>id(&quot;new&quot;)/div[@class=&quot;lookup&quot;]/div[@class=&quot;listRelatedObject lookupBlock&quot;]/div[@class=&quot;bPageBlock brandSecondaryBrd secondaryPalette&quot;]/div[@class=&quot;pbBody&quot;]/table[@class=&quot;list&quot;]/tbody[1]/tr[@class=&quot;dataRow even last first&quot;]/th[1]/a[@class=&quot;dataCell&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon-elementInfoDiv&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Search  Salesforce - Unlimited/frame_resultsFrame_2</value>
   </webElementProperties>
</WebElementEntity>
