<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Configure...</name>
   <tag></tag>
   <elementGuidId>ebaffa33-2d63-46b3-bcb3-43803330a85c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>catalogProduct.isConfigurable()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>catalogProduct.configure()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>catalogProduct.isAddAnotherButtonDisabled(catalogProduct.product.productSO.Id)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secondary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						Configure...
					</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[@class=&quot;content-container&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;layout--leftcol ng-scope&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;main-product-block block main-block ng-scope&quot;]/div[@class=&quot;main-product-listings&quot;]/div[@class=&quot;main-block__listings ng-scope&quot;]/ul[1]/li[1]/catalog-product[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;main__listings_item listing-item&quot;]/div[@class=&quot;listing-meta&quot;]/div[@class=&quot;listing-actions is--group&quot;]/div[@class=&quot;listing-actions-area ng-scope&quot;]/button[@class=&quot;secondary&quot;]</value>
   </webElementProperties>
</WebElementEntity>
