<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Product</name>
   <tag></tag>
   <elementGuidId>91293346-678f-47cf-96c5-33e87664e211</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-cart-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            
            
            
                
                
                    
                        
                            
                                Product
                                
                            
                            
                        
                            
                            
                                List Price
                            
                        
                            
                            
                                Base Price
                            
                        
                            
                            
                                Quantity
                            
                        
                            
                            
                                Delta Quantity
                            
                        
                            
                            
                                Selling Term
                            
                        
                            
                            
                                Start Date
                            
                        
                            
                            
                                End Date
                            
                        
                            
                            
                                Adjustment Type
                            
                        
                            
                            
                                Adjustment Amount
                            
                        
                            
                            
                                Net Unit Price
                            
                        
                            
                            
                                Allocation Percent
                            
                        
                            
                            
                                NNACV
                            
                        
                            
                            
                                RenewalACV
                            
                        
                            
                            
                                TCV
                            
                        
                            
                            
                                Flagged As MultiSelect
                            
                        
                    
                
                
                    
                        
                            
                            
                                
                                
                                    
                                        
                                        
                                            1
                                        
                                        
                                        
                                            
                                            
                                        
                                        
											
												Service Management Suite v2 With Performance Analytics - Fulfiller User
											
								
												build
												
											
							
                                    
                                    
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
														

	Subscription Fee



      												
                                                    
											
										
                                                    
                                                    
                                                    
                                        
                                                
                                            
                                        
                                        
                                            
                                                Show Options
                                                --None-- 
                                                        
                                                      
                                            
                                        
                                    
                                    
                                    
                                        
                                        
                                    
                                
                                
                            
                            
                            
                            
                            
                            
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	BRL 385.20



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	BRL 385.20



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

    

    






                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	5



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	12.00000



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    


    






                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    


    






                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    
--None-- 
			% Discount
		  



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

    

    






                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	BRL 385.20



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	0.00



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	BRL 23,112.00



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	BRL 0.00



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

	BRL 23,112.00



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                            
                            
                                
                                
                                
                                
                            
                            
                            
                            
                            
                                
                                    
                                    
                                
                                
                                    
                                        
                                            
                                                
                                                
                                                
                                                    
                                                    

			First Time Purchase
		 



                                                
                                                
                                            
                                        
                                        
                                        
                                    
                                
                            
                            
                            
                                
                                
                                    
                                        
                                    
                                
                                
                                
                                
                            
                        
                    
                
            
        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[@class=&quot;content-container&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;layout-single-col ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;main-cart-wrapper main-cart-wrapper--overflow ng-scope&quot;]/div[@class=&quot;main-cart-container--positioning&quot;]/div[@class=&quot;main-cart-container&quot;]</value>
   </webElementProperties>
</WebElementEntity>
