<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cart</name>
   <tag></tag>
   <elementGuidId>f07eede2-aeb0-4211-8bef-355587a407e1</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mini-cart__display__label ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			Cart
		</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[@class=&quot;header-global&quot;]/div[@class=&quot;ng-scope&quot;]/global-header[@class=&quot;ng-scope&quot;]/div[@class=&quot;right-blocks&quot;]/div[@class=&quot;ng-scope&quot;]/mini-cart[@class=&quot;mini-cart block ng-scope&quot;]/span[@class=&quot;mini-cart__display&quot;]/span[@class=&quot;mini-cart__display__label ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
