<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EASTMAJ-TER-3</name>
   <tag></tag>
   <elementGuidId>37061f8c-d6ad-4d6a-81c4-f9b442e3b7bd</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apt-focus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!vm.componentLayout.metaJson.quickViewConfig || vm.componentLayout.metaJson.quickViewConfig.disabled || (vm.componentLayout.metaJson.detailViewConfig &amp;&amp; !vm.componentLayout.metaJson.detatailViewConfig.disabled)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'refernce-link': (vm.componentLayout.metaJson.detailViewConfig &amp;&amp; !vm.componentLayout.metaJson.detailViewConfig.disabled)}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.navigateTo(vm.fieldId)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EASTMAJ-TER-3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;md-panel-outer-wrapper md-panel-is-showing&quot;]/md-tooltip[@class=&quot;ands-tooltip apt-quick-view-tooltip md-panel md-tooltip md-show md-origin-bottom _md-panel-position-adjusted&quot;]/div[@class=&quot;apt-quick-view-content&quot;]/div[@class=&quot;apt-extensible-component layout-1521091085014-17__custom layout-row&quot;]/div[@class=&quot;apt-container layout-row flex&quot;]/div[@class=&quot;apt-section section-1521091085014-47__internal draggable flex&quot;]/div[@class=&quot;children-inner&quot;]/div[@class=&quot;apt-component detailsView component-1521091085014-165__internal draggable&quot;]/div[@class=&quot;apt-fieldset&quot;]/apt-details[1]/div[@class=&quot;layout-row flex&quot;]/div[@class=&quot;apt-details layout-row flex&quot;]/div[@class=&quot;apt-section section-1521091085014-46__internal flex draggable&quot;]/div[@class=&quot;children-inner&quot;]/div[@class=&quot;apt-component detailsField component-1521091085014-169__internal draggable&quot;]/div[@class=&quot;apt-fieldset&quot;]/div[@class=&quot;apt-details-field&quot;]/div[@class=&quot;input-fieldset layout-column flex&quot;]/div[@class=&quot;inputs ands-medium apt-focus apt-detail-field-value&quot;]/div[1]/span[@class=&quot;apt-focus&quot;]</value>
   </webElementProperties>
</WebElementEntity>
