<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create Quote</name>
   <tag></tag>
   <elementGuidId>d385e92b-67b1-4920-8ece-dff802f23e6d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form_action_button header  action_context btn btn-default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>85f8fd75db0d0f0089a4ff9aae9619ae</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>var dummy_local_action_name=window.dummy_local_action_name;createQuote();return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>85f8fd75db0d0f0089a4ff9aae9619ae</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-name</name>
      <type>Main</type>
      <value>85f8fd75db0d0f0089a4ff9aae9619ae</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gsft_id</name>
      <type>Main</type>
      <value>85f8fd75db0d0f0089a4ff9aae9619ae</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Quote</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sales_opportunity.form_header&quot;)/span[@id=&quot;section_tab.d04344d32b97a10031a0ab84b4da15a0&quot;]/span[@id=&quot;section-d04344d32b97a10031a0ab84b4da15a0&quot;]/nav[@class=&quot;navbar navbar-default section_zero&quot;]/span[@class=&quot;ui_action_container_overflow&quot;]/span[@class=&quot;navbar_ui_actions&quot;]/button[@id=&quot;85f8fd75db0d0f0089a4ff9aae9619ae&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_QA_Instanceom_16  ServiceNow T/iframe_gsft_main</value>
   </webElementProperties>
</WebElementEntity>
