<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- None --AMDOCS Clarif</name>
   <tag></tag>
   <elementGuidId>ca9ee2f0-35c8-4083-9d6c-6acf378782b5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label.sales_opportunity.u_incumbent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-non-bindable</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sales_opportunity.u_incumbent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sales_opportunity.u_incumbent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>onChange('sales_opportunity.u_incumbent');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mandatory</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- None --AMDOCS ClarifyBMC NumaraCA Unicenter; BMCHP ServiceCenter, OtherManageEnginesNoneOther - HADSalesforceTelia with Genesys PureEngageVMWare InfrastructureAxiosBMCBMC MagicBMC Numara FootprintsBMC Numara TrackITBMC RemedyBMC RemedyForceBMC Remedy OnDemandC2 EnterpriseCACA NimsoftCA UnicenterChangeGearCherwellCiresonConnectwiseDell KaceEasyVistaEmailExcelFreshServiceFrontRangeFrontrange HeatFrontrange ITSMHelp Star ServiceProHomegrownHornbillHPHP ServiceAnywhereHP ServiceCenterHP ServiceDeskHP ServiceManagerIBMIBM Maximo/TivoliOSTicket.comJiraLANDeskNumaraSymantecLANDesk TouchpaperManageEngineMarvalMatrix 42Microsoft SCSMNo Previous SolutionOtherOTRSSalesforce.comSalesForce Desk.comSamanageSerenaService-now.comSharepointSolarWinds Web Help DeskSymantec AltirisSysAidVMWare InfraZenDesk</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sales_opportunity.u_incumbent&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_QA_Instanceom_16  ServiceNow T/iframe_gsft_main</value>
   </webElementProperties>
</WebElementEntity>
