<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QUO0762753-1  Quote for OPTY</name>
   <tag></tag>
   <elementGuidId>9885c710-6ee0-4721-aecd-9a62875963e9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-href</name>
      <type>Main</type>
      <value>https://servicenow-apttus11.apttuscloud.com/ui/cpq/quote/detail/41f3713b-3d21-e811-896b-00155d7fe074</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://servicenow-apttus11.apttuscloud.com/ui/cpq/quote/detail/41f3713b-3d21-e811-896b-00155d7fe074</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> QUO0762753-1 | Quote for OPTY0762753 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;apt-component global-sub-header-container ng-isolate-scope&quot;]/div[@class=&quot;apt-fieldset&quot;]/div[@class=&quot;global-sub-header-container__left-block&quot;]/div[@class=&quot;global-sub-header-container__buttons-btn ng-scope&quot;]/a[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
