<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QUO0753025-1  Quote for OPTY</name>
   <tag></tag>
   <elementGuidId>4fffcd01-c1cb-4234-9e42-d33fedb40cd2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-href</name>
      <type>Main</type>
      <value>https://servicenow-qa2.apttuscloud.com/ui/cpq/quote/detail/0b889e84-a61b-e811-80c2-0004ffb478af</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://servicenow-qa2.apttuscloud.com/ui/cpq/quote/detail/0b889e84-a61b-e811-80c2-0004ffb478af</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> QUO0753025-1 | Quote for OPTY0753025 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;apt-component global-sub-header-container ng-isolate-scope&quot;]/div[@class=&quot;apt-fieldset&quot;]/div[@class=&quot;global-sub-header-container__left-block&quot;]/div[@class=&quot;global-sub-header-container__buttons-btn ng-scope&quot;]/a[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
