<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_input-4 - Copy</name>
   <tag></tag>
   <elementGuidId>470b0423-17c1-468b-89f5-8286c703821a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;input-4&quot;)[count(. | //input[@type = 'search' and @id = 'input-4' and @ng-if = '!floatingLabel' and @autocomplete = 'off' and @ng-required = '$mdAutocompleteCtrl.isRequired' and @ng-disabled = '$mdAutocompleteCtrl.isDisabled' and @ng-readonly = '$mdAutocompleteCtrl.isReadonly' and @ng-model = '$mdAutocompleteCtrl.scope.searchText' and @ng-keydown = '$mdAutocompleteCtrl.keydown($event)' and @ng-blur = '$mdAutocompleteCtrl.blur($event)' and @ng-focus = '$mdAutocompleteCtrl.focus($event)' and @aria-owns = 'ul-4' and @aria-autocomplete = 'list' and @role = 'textbox' and @aria-haspopup = 'true' and @aria-expanded = 'false' and @class = 'ng-pristine ng-untouched ng-scope ng-empty ng-valid-minlength ng-valid-maxlength ng-valid ng-valid-required md-input' and @aria-invalid = 'false' and @tabindex = '0' and @aria-multiline = 'true']) = count(//input[@type = 'search' and @id = 'input-4' and @ng-if = '!floatingLabel' and @autocomplete = 'off' and @ng-required = '$mdAutocompleteCtrl.isRequired' and @ng-disabled = '$mdAutocompleteCtrl.isDisabled' and @ng-readonly = '$mdAutocompleteCtrl.isReadonly' and @ng-model = '$mdAutocompleteCtrl.scope.searchText' and @ng-keydown = '$mdAutocompleteCtrl.keydown($event)' and @ng-blur = '$mdAutocompleteCtrl.blur($event)' and @ng-focus = '$mdAutocompleteCtrl.focus($event)' and @aria-owns = 'ul-4' and @aria-autocomplete = 'list' and @role = 'textbox' and @aria-haspopup = 'true' and @aria-expanded = 'false' and @class = 'ng-pristine ng-untouched ng-scope ng-empty ng-valid-minlength ng-valid-maxlength ng-valid ng-valid-required md-input' and @aria-invalid = 'false' and @tabindex = '0' and @aria-multiline = 'true'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!floatingLabel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.isRequired</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.isDisabled</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.isReadonly</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.scope.searchText</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keydown</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.keydown($event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.blur($event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.focus($event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>ul-4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-scope ng-empty ng-valid-minlength ng-valid-maxlength ng-valid ng-valid-required md-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4&quot;)</value>
   </webElementProperties>
</WebElementEntity>
