<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>md-chips-wrap__md-chips-wrappe</name>
   <tag></tag>
   <elementGuidId>4b60b05b-bac9-4ea5-bb7d-80300ca15ae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;_md-chips-wrapper-3&quot;)[count(. | //md-chips-wrap[@id = '_md-chips-wrapper-3' and @tabindex = '-1' and @ng-keydown = '$mdChipsCtrl.chipKeydown($event)' and @ng-class = concat('{ ' , &quot;'&quot; , 'md-focused' , &quot;'&quot; , ': $mdChipsCtrl.hasFocus(), 	                      ' , &quot;'&quot; , 'md-readonly' , &quot;'&quot; , ': !$mdChipsCtrl.ngModelCtrl || $mdChipsCtrl.readonly,	                      ' , &quot;'&quot; , 'md-removable' , &quot;'&quot; , ': $mdChipsCtrl.isRemovable() }') and @aria-setsize = '0' and @class = 'md-chips md-removable md-focused']) = count(//md-chips-wrap[@id = '_md-chips-wrapper-3' and @tabindex = '-1' and @ng-keydown = '$mdChipsCtrl.chipKeydown($event)' and @ng-class = concat('{ ' , &quot;'&quot; , 'md-focused' , &quot;'&quot; , ': $mdChipsCtrl.hasFocus(), 	                      ' , &quot;'&quot; , 'md-readonly' , &quot;'&quot; , ': !$mdChipsCtrl.ngModelCtrl || $mdChipsCtrl.readonly,	                      ' , &quot;'&quot; , 'md-removable' , &quot;'&quot; , ': $mdChipsCtrl.isRemovable() }') and @aria-setsize = '0' and @class = 'md-chips md-removable md-focused'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-chips-wrap</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_md-chips-wrapper-3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keydown</name>
      <type>Main</type>
      <value>$mdChipsCtrl.chipKeydown($event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'md-focused': $mdChipsCtrl.hasFocus(), 	                      'md-readonly': !$mdChipsCtrl.ngModelCtrl || $mdChipsCtrl.readonly,	                      'md-removable': $mdChipsCtrl.isRemovable() }</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-chips md-removable md-focused</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_md-chips-wrapper-3&quot;)</value>
   </webElementProperties>
</WebElementEntity>
