<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Default</name>
   <tag></tag>
   <elementGuidId>012de4f4-6e44-4c04-b763-6ccc9a5051dd</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;modal fade ng-isolate-scope templates-dialog in&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body sel-tpl__body ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;templates&quot;]/div[@class=&quot;templates__table&quot;]/div[1]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;ng-scope ng-isolate-scope st-selected&quot;]/td[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
