<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_md-on</name>
   <tag></tag>
   <elementGuidId>9dc9d444-9477-43ea-8568-6311a309c4fa</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generateDocument-template-table&quot;)/tbody[1]/tr[1]/td[@class=&quot;ands-align-center&quot;]/div[@class=&quot;radio-group ands-input-container&quot;]/md-radio-group[@class=&quot;ng-valid _md ng-not-empty ng-dirty ng-touched ng-valid-parse&quot;]/md-radio-button[@id=&quot;generateDocument-select-radio&quot;]/div[@class=&quot;md-container&quot;]/div[@class=&quot;md-on&quot;]</value>
   </webElementProperties>
</WebElementEntity>
