<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_md-container</name>
   <tag></tag>
   <elementGuidId>c3b23790-3227-422f-9281-e3e01c16db85</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid-container-11078431724815418&quot;)/apt-data-grid[@class=&quot;un-paginated layout-column&quot;]/div[@class=&quot;apt-data-grid layout-column&quot;]/div[@class=&quot;apt-data-grid-contents-wrapper layout-row&quot;]/apt-data-grid-render-container[@class=&quot;layout-column&quot;]/div[@class=&quot;apt-data-grid-render-container&quot;]/apt-data-grid-viewport[@class=&quot;layout-column&quot;]/div[@class=&quot;apt-data-grid-viewport layout-column&quot;]/div[@class=&quot;apt-data-grid-canvas&quot;]/apt-data-grid-row[@class=&quot;layout-row&quot;]/div[@class=&quot;apt-data-grid-row-container flex&quot;]/div[@class=&quot;apt-data-grid-row layout-row flex&quot;]/apt-data-grid-cell[1]/div[@class=&quot;apt-data-grid-cell-contents cell-selection&quot;]/md-checkbox[@class=&quot;ands-checkbox ng-pristine ng-untouched ng-valid ng-empty&quot;]/div[@class=&quot;md-container&quot;]</value>
   </webElementProperties>
</WebElementEntity>
