<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Note</name>
   <tag></tag>
   <elementGuidId>37f586ad-d027-4f4e-932b-bb8337158fa4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inner-cell</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>apt-hover-info</name>
      <type>Main</type>
      <value>Note</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>apt-hover-options</name>
      <type>Main</type>
      <value>vm.hoverOptions</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Note</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid-container-5260133789580714&quot;)/apt-data-grid[@class=&quot;un-paginated layout-column&quot;]/div[@class=&quot;apt-data-grid layout-column&quot;]/div[@class=&quot;apt-data-grid-contents-wrapper layout-row&quot;]/apt-data-grid-render-container[@class=&quot;layout-column&quot;]/div[@class=&quot;apt-data-grid-render-container&quot;]/apt-data-grid-header[@class=&quot;layout-column flex&quot;]/div[@class=&quot;apt-data-grid-header-viewport&quot;]/div[@class=&quot;apt-data-grid-header-canvas&quot;]/div[@class=&quot;apt-data-grid-header layout-row flex&quot;]/apt-data-grid-header-cell[@class=&quot;apt-focus&quot;]/div[@class=&quot;apt-data-grid-header-cell-contents&quot;]/div[@class=&quot;inner-cell&quot;]</value>
   </webElementProperties>
</WebElementEntity>
