<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_md-off_1</name>
   <tag></tag>
   <elementGuidId>25e05b12-687b-4ebd-987e-ce14cdebfbf7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generateDocument-template-table&quot;)/tbody[1]/tr[2]/td[@class=&quot;ands-align-center&quot;]/div[@class=&quot;radio-group ands-input-container&quot;]/md-radio-group[@class=&quot;ng-pristine ng-untouched ng-valid _md ng-not-empty&quot;]/md-radio-button[@id=&quot;generateDocument-select-radio&quot;]/div[@class=&quot;md-container&quot;]/div[@class=&quot;md-off&quot;]</value>
   </webElementProperties>
</WebElementEntity>
