<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Generate</name>
   <tag></tag>
   <elementGuidId>5231a419-551c-4cff-9355-d0494a3d3bc7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate
		</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;clm layout-fill layout-column&quot;]/main[@class=&quot;page-main flex&quot;]/div[1]/section[@class=&quot;agreement-details&quot;]/div[@class=&quot;apt-extensible-component layout-row layout-1520574472483-2__custom&quot;]/div[@class=&quot;apt-container layout-row flex&quot;]/div[@class=&quot;apt-section section-1520574472483-28__internal flex draggable&quot;]/div[@class=&quot;children-inner&quot;]/div[@class=&quot;apt-section section-1520574472482-0__internal draggable&quot;]/div[@class=&quot;children-inner&quot;]/div[@class=&quot;apt-component actionBar component-1520574472482-3__internal draggable&quot;]/div[@class=&quot;apt-fieldset&quot;]/apt-action-bar[1]/div[@class=&quot;apt-action-bar&quot;]/div[@class=&quot;apt-actions layout-wrap layout-align-end-center layout-row&quot;]/div[@class=&quot;apt-action&quot;]/div[@class=&quot;apt-component entityActions component-1520574468462-0__internal draggable&quot;]/div[@class=&quot;apt-fieldset&quot;]/div[@class=&quot;entity-actions-container layout-align-end-center layout-row&quot;]/div[@class=&quot;layout-wrap layout-align-end-center layout-row&quot;]/button[@class=&quot;ands-btn ands-primary md-button&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
