<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_-</name>
   <tag></tag>
   <elementGuidId>c59ddca7-5017-4829-98af-70d2883f6d10</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid-container-4688081413704701&quot;)/apt-data-grid[@class=&quot;layout-column paginated&quot;]/div[@class=&quot;apt-data-grid layout-column&quot;]/div[@class=&quot;apt-data-grid-contents-wrapper layout-row&quot;]/apt-data-grid-render-container[@class=&quot;layout-column&quot;]/div[@class=&quot;apt-data-grid-render-container&quot;]/apt-data-grid-viewport[@class=&quot;layout-column&quot;]/div[@class=&quot;apt-data-grid-viewport layout-column&quot;]/div[@class=&quot;apt-data-grid-canvas&quot;]/apt-data-grid-row[@class=&quot;layout-row&quot;]/div[@class=&quot;apt-data-grid-row-container flex&quot;]/div[@class=&quot;apt-data-grid-row layout-row flex&quot;]/apt-data-grid-cell[2]/div[@class=&quot;apt-data-grid-cell-contents cell-data flex&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;cell-value apt-focus&quot;]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
