<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>first approver</name>
   <tag></tag>
   <elementGuidId>a15af1ed-5cc4-4a78-83ab-c4c734592d63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>((//MD-ICON[@md-menu-origin=''][text()='more_vert'][text()='more_vert'])[1]/../../../../..//MD-ICON[@md-menu-origin=''][text()='more_vert'][text()='more_vert'][text()='more_vert'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ands-icon-material ands-icons action material-icons</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/md-list[@class=&quot;approval-activity flex&quot;]/md-list-item[@class=&quot;md-2-line seq with-time&quot;]/div[@class=&quot;md-no-style md-list-item-inner&quot;]/md-menu[@class=&quot;rule-option md-menu _md&quot;]/button[@class=&quot;ands-btn--icon md-icon-button md-button&quot;]/md-icon[@class=&quot;ands-icon-material ands-icons action material-icons&quot;]</value>
   </webElementProperties>
</WebElementEntity>
