<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_md-datepicker-input</name>
   <tag></tag>
   <elementGuidId>8a621a9a-52ee-4d05-a0a1-957ba97e2c59</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-datepicker-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>ctrl.setFocused(true)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>ctrl.setFocused(false)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;cpq layout-fill layout-column&quot;]/main[@class=&quot;page-main flex&quot;]/div[1]/div[@class=&quot;quote md-inline-form layout-column&quot;]/div[@class=&quot;apt-extensible-component layout-row layout-1519727981514-3__custom&quot;]/div[@class=&quot;apt-container layout-row flex&quot;]/div[@class=&quot;apt-section section-1519727981514-8__internal flex draggable&quot;]/div[@class=&quot;children-inner&quot;]/div[@class=&quot;apt-component formView component-1519727981514-4__internal draggable&quot;]/div[@class=&quot;apt-fieldset&quot;]/apt-form[1]/div[@class=&quot;layout-row flex&quot;]/form[@class=&quot;apt-form ng-pristine ng-valid-maxlength ng-invalid ng-invalid-required ng-valid-minlength ng-valid-mindate ng-valid-maxdate ng-valid-filtered ng-valid-valid ng-valid-max layout-row flex ng-valid-apt-validation-message&quot;]/div[@class=&quot;apt-section section-1519727981514-7__internal draggable flex&quot;]/div[@class=&quot;children-inner&quot;]/div[@class=&quot;apt-section section-1519727981514-0__internal draggable&quot;]/div[@class=&quot;children-inner&quot;]/div[@class=&quot;apt-component formField component-1519727981514-22__internal draggable&quot;]/div[@class=&quot;apt-fieldset&quot;]/div[@class=&quot;apt-form-field&quot;]/div[@class=&quot;input-fieldset&quot;]/apt-date-input-field[@class=&quot;inputs ng-pristine ng-untouched ng-valid ng-empty layout-column&quot;]/div[@class=&quot;layout-column&quot;]/div[@class=&quot;apt-input-container ands-datepicker-container&quot;]/div[@class=&quot;apt-input-row layout-row&quot;]/apt-date-picker[@class=&quot;ng-pristine ng-untouched ng-empty ng-valid ng-valid-required layout-row flex&quot;]/md-datepicker[@class=&quot;ands-datepicker ng-pristine ng-untouched _md-datepicker-has-triangle-icon ng-valid-mindate ng-valid-maxdate ng-valid-filtered ng-valid-valid ng-empty ng-invalid ng-invalid-required layout-row flex&quot;]/div[@class=&quot;md-datepicker-input-container md-datepicker-focused&quot;]/input[@class=&quot;md-datepicker-input&quot;]</value>
   </webElementProperties>
</WebElementEntity>
