<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>md-icon_more_vert</name>
   <tag></tag>
   <elementGuidId>932668c6-0704-425d-8286-9ef914b524f6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>more button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ands-icon-material ands-icons material-icons</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;cpq layout-fill layout-column&quot;]/main[@class=&quot;page-main flex&quot;]/div[1]/section[@class=&quot;quote-details&quot;]/div[@class=&quot;apt-extensible-component layout-row layout-1521097335982-3__custom&quot;]/div[@class=&quot;apt-container layout-row flex&quot;]/div[@class=&quot;apt-section section-1521097335982-20__internal flex draggable&quot;]/div[@class=&quot;children-inner&quot;]/div[@class=&quot;apt-section section-1521097335980-0__internal draggable&quot;]/div[@class=&quot;children-inner&quot;]/div[@class=&quot;apt-component actionBar component-1521097335980-3__internal draggable&quot;]/div[@class=&quot;apt-fieldset&quot;]/apt-action-bar[1]/div[@class=&quot;apt-action-bar&quot;]/div[@class=&quot;apt-actions layout-wrap layout-align-end-center layout-row&quot;]/div[@class=&quot;apt-action&quot;]/div[@class=&quot;apt-component entityActions component-1521097332784-0__internal draggable&quot;]/div[@class=&quot;apt-fieldset&quot;]/div[@class=&quot;entity-actions-container layout-align-end-center layout-row&quot;]/md-menu[@class=&quot;md-menu _md&quot;]/button[@class=&quot;apt-focus ands-btn--icon md-button&quot;]/md-icon[@class=&quot;ands-icon-material ands-icons material-icons&quot;]</value>
   </webElementProperties>
</WebElementEntity>
