<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Draft</name>
   <tag></tag>
   <elementGuidId>38899ed5-53dc-45bb-a001-0a4a59ce82e0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;cpq layout-fill layout-column&quot;]/main[@class=&quot;page-main flex&quot;]/div[1]/section[@class=&quot;quote-details&quot;]/div[@class=&quot;apt-extensible-component layout-row layout-1520597768545-2__custom&quot;]/div[@class=&quot;apt-container layout-row flex&quot;]/div[@class=&quot;apt-section section-1520597768545-18__internal flex draggable&quot;]/div[@class=&quot;children-inner&quot;]/div[@class=&quot;apt-section section-1520597768545-17__internal draggable&quot;]/div[@class=&quot;children-inner&quot;]/div[@class=&quot;apt-section section-1520597768544-8__internal draggable&quot;]/div[@class=&quot;children-inner&quot;]/div[@class=&quot;apt-component quoteDetailHeader component-1520597768544-4__internal draggable&quot;]/div[@class=&quot;apt-fieldset&quot;]/quote-detail-header[1]/header[@class=&quot;quote-detail-header-section layout-margin layout-column&quot;]/div[@class=&quot;flex&quot;]/cpq-chevron[1]/div[@class=&quot;cpq-chevron-container&quot;]/div[@class=&quot;cpq-chevron&quot;]/span[@class=&quot;text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
