<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Approve</name>
   <tag></tag>
   <elementGuidId>a26b8f4c-362a-4f6a-a3a6-922a2d3764a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//SPAN[text()='Approve'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_container_224&quot;)/md-menu-content[1]/md-menu-item[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
